spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cdc
    username: cdc
    password: cdc
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
#    generate-ddl: true
#    hibernate:
#      dll-auto: update